;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	haskell-indentation-common-electric-command
	save-some-buffers
	upcase-region
	))

(setq mc/cmds-to-run-once
      '(
	ensime-mouse-motion
	mac-mwheel-scroll
	sp-remove-active-pair-overlay
	yaml-electric-backspace
	))
